# Generated by Django 4.0.4 on 2022-05-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='user',
        ),
        migrations.AddField(
            model_name='drink',
            name='username',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
