# Generated by Django 4.0.4 on 2022-05-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_remove_drink_user_drink_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drink_image',
            field=models.CharField(default='None', max_length=400),
        ),
        migrations.AddField(
            model_name='drink',
            name='drink_instructions',
            field=models.CharField(default='None', max_length=600),
        ),
        migrations.AddField(
            model_name='drink',
            name='drink_name',
            field=models.CharField(default='None', max_length=200, unique=True),
        ),
    ]
