# Generated by Django 4.0.4 on 2022-05-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_drink_drink_image_drink_drink_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
